"""add_is_admin_field

Revision ID: 01e3bc407d4e
Revises: 3736a7a26842
Create Date: 2026-02-04 15:49:41.798729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e3bc407d4e'
down_revision: Union[str, Sequence[str], None] = '3736a7a26842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # vusal@test.com hesabini admin et
    op.execute("UPDATE users SET is_admin = true WHERE email = 'vusal@test.com'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
