"""add trainer verification fields

Revision ID: 3769078e7521
Revises: c066e716f314
Create Date: 2026-02-01 23:29:50.397475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3769078e7521'
down_revision: Union[str, Sequence[str], None] = 'c066e716f314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram_handle', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('verification_photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('verification_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('verification_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_verification_attempt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_attempt')
    op.drop_column('users', 'verification_attempts')
    op.drop_column('users', 'verification_score')
    op.drop_column('users', 'verification_photo_url')
    op.drop_column('users', 'instagram_handle')
    # ### end Alembic commands ###
