"""add_routes_table

Revision ID: 43943a7b649d
Revises: b7e9e692e75a
Create Date: 2026-02-01 13:49:21.476747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43943a7b649d'
down_revision: Union[str, Sequence[str], None] = 'b7e9e692e75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('workout_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=False),
    sa.Column('start_longitude', sa.Float(), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('coordinates_json', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('max_pace', sa.Float(), nullable=True),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=True),
    sa.Column('max_speed_kmh', sa.Float(), nullable=True),
    sa.Column('elevation_gain', sa.Float(), nullable=True),
    sa.Column('elevation_loss', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('static_map_url', sa.String(length=500), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.Column('assigned_by_id', sa.String(), nullable=True),
    sa.Column('assignment_notes', sa.String(length=500), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_user_id'), 'routes', ['user_id'], unique=False)
    op.create_index(op.f('ix_routes_workout_id'), 'routes', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_workout_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_user_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
