"""add_settings_bookmarks_social

Revision ID: a1b2c3d4e5f6
Revises: f1a2b3c4d5e6
Create Date: 2026-02-21 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create user_settings and news_bookmarks tables (if not exist)."""
    conn = op.get_bind()

    # user_settings — artıq mövcuddursa, yaratma
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_settings')"
    ))
    if not result.scalar():
        op.create_table('user_settings',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('workout_reminders', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('meal_reminders', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('weekly_reports', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('language', sa.String(length=10), nullable=False, server_default='az'),
        sa.Column('dark_mode', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )
        op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)

    # news_bookmarks — artıq mövcuddursa, yaratma
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'news_bookmarks')"
    ))
    if not result.scalar():
        op.create_table('news_bookmarks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('article_id', sa.String(), nullable=False),
        sa.Column('article_title', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'article_id', name='uq_user_article_bookmark')
        )
        op.create_index(op.f('ix_news_bookmarks_user_id'), 'news_bookmarks', ['user_id'], unique=False)
        op.create_index(op.f('ix_news_bookmarks_article_id'), 'news_bookmarks', ['article_id'], unique=False)


def downgrade() -> None:
    """Drop news_bookmarks and user_settings tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_bookmarks_article_id'), table_name='news_bookmarks')
    op.drop_index(op.f('ix_news_bookmarks_user_id'), table_name='news_bookmarks')
    op.drop_table('news_bookmarks')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
